package wz_pkg

type AutoGenerated struct {
	Type     string `json:"type"`
	Features []struct {
		Type       string `json:"type"`
		Properties struct {
			ID             string `json:"id"`
			Name           string `json:"name"`
			Phone          string `json:"phone"`
			Address        string `json:"address"`
			MaskAdult      int    `json:"mask_adult"`
			MaskChild      int    `json:"mask_child"`
			Updated        string `json:"updated"`
			Available      string `json:"available"`
			Note           string `json:"note"`
			CustomNote     string `json:"custom_note"`
			Website        string `json:"website"`
			County         string `json:"county"`
			Town           string `json:"town"`
			Cunli          string `json:"cunli"`
			ServicePeriods string `json:"service_periods"`
		} `json:"properties"`
		Geometry struct {
			Type        string    `json:"type"`
			Coordinates []float64 `json:"coordinates"`
		} `json:"geometry"`
	} `json:"features"`
}
